import type { DashboardMockData } from "./dashboardTypes";

export const dashboardMockData: DashboardMockData = {
  customer: {
    name: "Daan Koote",
    email: "daankoote@gmail.com",
  },
  assets: [
    {
      id: "asset-private-home",
      type: "private_home",
      typeLabel: "Privéwoning",
      name: "Privéwoning",
      identity: "Kostverlorenstraat 65 — 2042PC — Zandvoort — Nederland",
      status: "needs_customer_action",
      statusLabel: "Actie nodig",
      locationsCount: 1,
      chargersCount: 2,
      openActions: 2,
      nextAction: "Upload energierekening",
      documents: [
        { id: "doc-address", title: "Adresbewijs", status: "Akkoord" },
        { id: "doc-installation", title: "Installatiefactuur", status: "Akkoord" },
        { id: "doc-mid", title: "MID bewijs", status: "In review" },
        { id: "doc-kwh", title: "kWh 2026", status: "Ontbreekt" },
      ],
      chargers: [
        { id: "charger-1", label: "Laadpaal 1", midNumber: "MID 123456", status: "In review" },
        { id: "charger-2", label: "Laadpaal 2", midNumber: "MID ontbreekt", status: "Actie nodig" },
      ],
      timeline: [
        { id: "tl-1", label: "Dossier gestart", date: "12 jun 2026", status: "Gereed" },
        { id: "tl-2", label: "Gegevens ontvangen", date: "12 jun 2026", status: "Gereed" },
        { id: "tl-3", label: "Adres gecontroleerd", date: "13 jun 2026", status: "Akkoord" },
        { id: "tl-4", label: "ENVAL vraagt aanvullende informatie", date: "16 jun 2026", status: "Open" },
        { id: "tl-5", label: "Dossier in beoordeling", date: "Later", status: "Gepland" },
      ],
      consents: [
        { id: "consent-privacy", title: "Privacy en gegevensverwerking", status: "Akkoord", version: "concept-v1" },
        { id: "consent-fee", title: "10% succesfee", status: "Akkoord", version: "concept-v1" },
        { id: "consent-mandate", title: "Toestemming controle", status: "Akkoord", version: "concept-v1" },
      ],
      valueYears: [
        {
          year: "2025",
          mode: "handled",
          kwh: "3.420 kWh",
          grossValue: "€ 342",
          externalCosts: "€ 28",
          envalFee: "€ 34",
          netCustomerResult: "€ 280",
          status: "Afgehandeld",
        },
        {
          year: "2026",
          mode: "running",
          kwh: "Nog nodig",
          grossValue: "Indicatief",
          externalCosts: "Nog onbekend",
          envalFee: "Alleen bij resultaat",
          netCustomerResult: "Indicatief",
          status: "kWh nodig",
        },
      ],
    },
    {
      id: "asset-business",
      type: "business",
      typeLabel: "Bedrijf",
      name: "BOHA Bali RED PT PMA",
      identity: "KVK 12345678",
      status: "under_review",
      statusLabel: "In beoordeling",
      locationsCount: 2,
      chargersCount: 4,
      openActions: 0,
      nextAction: "ENVAL beoordeelt de gegevens",
      documents: [
        { id: "doc-kvk", title: "KVK-uittreksel", status: "Akkoord" },
        { id: "doc-invoices", title: "Installatiefacturen", status: "In review" },
      ],
      chargers: [
        { id: "charger-business-1", label: "Locatie 1 — laadpaal 1", midNumber: "MID 827100", status: "Akkoord" },
        { id: "charger-business-2", label: "Locatie 2 — laadpaal 1", midNumber: "MID 827101", status: "In review" },
      ],
      timeline: [
        { id: "tl-business-1", label: "Dossier gestart", date: "8 jun 2026", status: "Gereed" },
        { id: "tl-business-2", label: "Documenten ontvangen", date: "9 jun 2026", status: "Gereed" },
        { id: "tl-business-3", label: "Dossier in beoordeling", date: "10 jun 2026", status: "Lopend" },
      ],
      consents: [
        { id: "consent-business-privacy", title: "Privacy en verwerking", status: "Akkoord", version: "concept-v1" },
        { id: "consent-business-fee", title: "Feevoorwaarden", status: "Akkoord", version: "concept-v1" },
      ],
      valueYears: [
        {
          year: "2026",
          mode: "running",
          kwh: "Nog nodig",
          grossValue: "Indicatief",
          externalCosts: "Nog onbekend",
          envalFee: "Alleen bij resultaat",
          netCustomerResult: "Indicatief",
          status: "In beoordeling",
        },
      ],
    },
    {
      id: "asset-vve",
      type: "vve",
      typeLabel: "VVE",
      name: "VVE example",
      identity: "Collectieve laadlocatie",
      status: "submitted",
      statusLabel: "Ingediend",
      locationsCount: 1,
      chargersCount: 6,
      openActions: 1,
      nextAction: "Controleer MID nummer",
      documents: [
        { id: "doc-vve-kvk", title: "KVK-uittreksel VVE", status: "Akkoord" },
        { id: "doc-vve-mid", title: "MID bewijs", status: "Aanvulling nodig" },
      ],
      chargers: [
        { id: "charger-vve-1", label: "Garage — laadpaal 1", midNumber: "MID 661010", status: "In review" },
        { id: "charger-vve-2", label: "Garage — laadpaal 2", midNumber: "MID 661011", status: "In review" },
      ],
      timeline: [
        { id: "tl-vve-1", label: "Dossier gestart", date: "18 jun 2026", status: "Gereed" },
        { id: "tl-vve-2", label: "Gegevens ontvangen", date: "18 jun 2026", status: "Gereed" },
        { id: "tl-vve-3", label: "ENVAL vraagt aanvullende informatie", date: "20 jun 2026", status: "Open" },
      ],
      consents: [
        { id: "consent-vve-mandate", title: "VVE toestemming", status: "Akkoord", version: "concept-v1" },
      ],
      valueYears: [
        {
          year: "2026",
          mode: "running",
          kwh: "Nog nodig",
          grossValue: "Indicatief",
          externalCosts: "Nog onbekend",
          envalFee: "Alleen bij resultaat",
          netCustomerResult: "Indicatief",
          status: "MID in review",
        },
      ],
    },
    {
      id: "asset-second-home",
      type: "second_home",
      typeLabel: "Tweede woning",
      name: "Tweede woning",
      identity: "Voorbeeldstraat 12 — 1234AB — Haarlem — Nederland",
      status: "year_kwh_required",
      statusLabel: "kWh nodig",
      locationsCount: 1,
      chargersCount: 1,
      openActions: 1,
      nextAction: "Vul kWh 2026 in",
      documents: [
        { id: "doc-second-invoice", title: "Installatiefactuur", status: "Akkoord" },
        { id: "doc-second-kwh", title: "kWh 2026", status: "Ontbreekt" },
      ],
      chargers: [
        { id: "charger-second-1", label: "Oprit — laadpaal 1", midNumber: "MID 551090", status: "Akkoord" },
      ],
      timeline: [
        { id: "tl-second-1", label: "Dossier gestart", date: "5 jun 2026", status: "Gereed" },
        { id: "tl-second-2", label: "Adres gecontroleerd", date: "6 jun 2026", status: "Akkoord" },
        { id: "tl-second-3", label: "kWh opgave gevraagd", date: "1 jul 2026", status: "Open" },
      ],
      consents: [
        { id: "consent-second-privacy", title: "Privacy en verwerking", status: "Akkoord", version: "concept-v1" },
      ],
      valueYears: [
        {
          year: "2026",
          mode: "running",
          kwh: "Nog nodig",
          grossValue: "Indicatief",
          externalCosts: "Nog onbekend",
          envalFee: "Alleen bij resultaat",
          netCustomerResult: "Indicatief",
          status: "kWh nodig",
        },
      ],
    },
  ],
  requests: [
    {
      id: "request-energy-bill",
      assetId: "asset-private-home",
      title: "Upload energierekening",
      scope: "Privéwoning",
      status: "Open",
      urgency: "Nodig voor adrescontrole",
      actionLabel: "Uploaden",
    },
    {
      id: "request-mid",
      assetId: "asset-vve",
      title: "Controleer MID nummer",
      scope: "VVE example",
      status: "Open",
      urgency: "Aanvulling gevraagd",
      actionLabel: "Aanvullen",
    },
    {
      id: "request-kwh",
      assetId: "asset-second-home",
      title: "Vul kWh 2026 in",
      scope: "Tweede woning",
      status: "Open",
      urgency: "Lopend jaar",
      actionLabel: "Vul kWh in",
    },
  ],
};
